[[redirects]]
    from = "docs/*"
    to = "https://hedges-docs.netlify.app/docs/:splat"
    status = 200
    force = true

[[redirects]]
    from = "blog/*"
    to = "https://hedges-blog.netlify.app/blog/:splat"
    status = 200
    force = true

[[redirects]]
    from = "shop/*"
    to = "https://hedges-products.netlify.app/shop/:splat"
    force = true
    status = 200
