[[redirects]]
    from = "docs"
    to = "https://hedges-docs.netlify.app"
    status = 200
    force = true

[[redirects]]
from = "blog"
to = "https://hedges-blog.netlify.app"
status = 200
force = true

[[redirects]]
from = "products/*"
to = "https://hedges-products.netlify.app/:splat"
status = 200
force = true